#!/usr/bin/python

import sys
import os
import socket
from optparse import OptionParser

sys.path.append("/prodloops/lib/python2/")
import db


def rSubmit(**fields):
  keys = fields.keys()
  keys.sort()
  cols = ""
  values = ""
  for key in keys:
    cols = cols + str(key).rstrip().lstrip()+ ","
    values = values +"\""+ str(fields[key]).rstrip().lstrip() +"\""+ ","
  col = cols.rstrip(",")
  value = values.rstrip(",")
  print("INSERT INTO tasks ("+ col +") VALUES ("+ value +")")
  
  #try:
    #conn = db.connRbhus()
    #cursor = conn.cursor()
    #cursor.execute("INSERT INTO tasks ()")
    #cursor.close()
    #conn.close()
    
rSubmit(name="shrinidhi",age=27)