# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingMod.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loading(object):
    def setupUi(self, loading):
        loading.setObjectName("loading")
        loading.setWindowModality(QtCore.Qt.WindowModal)
        loading.resize(400, 31)
        self.gridLayout = QtWidgets.QGridLayout(loading)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(loading)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)

        self.retranslateUi(loading)
        QtCore.QMetaObject.connectSlotsByName(loading)

    def retranslateUi(self, loading):
        _translate = QtCore.QCoreApplication.translate
        loading.setWindowTitle(_translate("loading", "in progress"))
