# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusSubmitMod.ui'
#
# Created: Thu Jan 17 20:02:17 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_rbhusSubmit(object):
  def setupUi(self, rbhusSubmit):
    rbhusSubmit.setObjectName(_fromUtf8("rbhusSubmit"))
    rbhusSubmit.resize(462, 529)
    self.centralwidget = QtGui.QWidget(rbhusSubmit)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.labelOsType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelOsType.sizePolicy().hasHeightForWidth())
    self.labelOsType.setSizePolicy(sizePolicy)
    self.labelOsType.setObjectName(_fromUtf8("labelOsType"))
    self.gridLayout.addWidget(self.labelOsType, 12, 0, 1, 1)
    self.comboPrio = QtGui.QComboBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboPrio.sizePolicy().hasHeightForWidth())
    self.comboPrio.setSizePolicy(sizePolicy)
    self.comboPrio.setObjectName(_fromUtf8("comboPrio"))
    self.comboPrio.addItem(_fromUtf8(""))
    self.comboPrio.addItem(_fromUtf8(""))
    self.comboPrio.addItem(_fromUtf8(""))
    self.gridLayout.addWidget(self.comboPrio, 15, 1, 1, 1)
    self.labelMinBatch = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelMinBatch.sizePolicy().hasHeightForWidth())
    self.labelMinBatch.setSizePolicy(sizePolicy)
    self.labelMinBatch.setObjectName(_fromUtf8("labelMinBatch"))
    self.gridLayout.addWidget(self.labelMinBatch, 18, 0, 1, 1)
    self.labelImageType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelImageType.sizePolicy().hasHeightForWidth())
    self.labelImageType.setSizePolicy(sizePolicy)
    self.labelImageType.setObjectName(_fromUtf8("labelImageType"))
    self.gridLayout.addWidget(self.labelImageType, 3, 0, 1, 1)
    self.labelImageName = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelImageName.sizePolicy().hasHeightForWidth())
    self.labelImageName.setSizePolicy(sizePolicy)
    self.labelImageName.setObjectName(_fromUtf8("labelImageName"))
    self.gridLayout.addWidget(self.labelImageName, 2, 0, 1, 1)
    self.labelMaxBatch = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelMaxBatch.sizePolicy().hasHeightForWidth())
    self.labelMaxBatch.setSizePolicy(sizePolicy)
    self.labelMaxBatch.setObjectName(_fromUtf8("labelMaxBatch"))
    self.gridLayout.addWidget(self.labelMaxBatch, 19, 0, 1, 1)
    self.labelLayer = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelLayer.sizePolicy().hasHeightForWidth())
    self.labelLayer.setSizePolicy(sizePolicy)
    self.labelLayer.setObjectName(_fromUtf8("labelLayer"))
    self.gridLayout.addWidget(self.labelLayer, 11, 0, 1, 1)
    self.pushFileName = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushFileName.sizePolicy().hasHeightForWidth())
    self.pushFileName.setSizePolicy(sizePolicy)
    self.pushFileName.setObjectName(_fromUtf8("pushFileName"))
    self.gridLayout.addWidget(self.pushFileName, 0, 2, 1, 1)
    self.labeRenderer = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labeRenderer.sizePolicy().hasHeightForWidth())
    self.labeRenderer.setSizePolicy(sizePolicy)
    self.labeRenderer.setObjectName(_fromUtf8("labeRenderer"))
    self.gridLayout.addWidget(self.labeRenderer, 9, 0, 1, 1)
    self.lineEditOutDir = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditOutDir.sizePolicy().hasHeightForWidth())
    self.lineEditOutDir.setSizePolicy(sizePolicy)
    self.lineEditOutDir.setToolTip(_fromUtf8(""))
    self.lineEditOutDir.setDragEnabled(True)
    self.lineEditOutDir.setObjectName(_fromUtf8("lineEditOutDir"))
    self.gridLayout.addWidget(self.lineEditOutDir, 1, 1, 1, 1)
    self.spinMinBatch = QtGui.QSpinBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.spinMinBatch.sizePolicy().hasHeightForWidth())
    self.spinMinBatch.setSizePolicy(sizePolicy)
    self.spinMinBatch.setMinimum(1)
    self.spinMinBatch.setMaximum(999999999)
    self.spinMinBatch.setObjectName(_fromUtf8("spinMinBatch"))
    self.gridLayout.addWidget(self.spinMinBatch, 18, 1, 1, 1)
    self.labelDescription = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDescription.sizePolicy().hasHeightForWidth())
    self.labelDescription.setSizePolicy(sizePolicy)
    self.labelDescription.setObjectName(_fromUtf8("labelDescription"))
    self.gridLayout.addWidget(self.labelDescription, 20, 0, 1, 1)
    self.labelHostGroup = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelHostGroup.sizePolicy().hasHeightForWidth())
    self.labelHostGroup.setSizePolicy(sizePolicy)
    self.labelHostGroup.setObjectName(_fromUtf8("labelHostGroup"))
    self.gridLayout.addWidget(self.labelHostGroup, 7, 0, 1, 1)
    self.labelOutDir = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelOutDir.sizePolicy().hasHeightForWidth())
    self.labelOutDir.setSizePolicy(sizePolicy)
    self.labelOutDir.setObjectName(_fromUtf8("labelOutDir"))
    self.gridLayout.addWidget(self.labelOutDir, 1, 0, 1, 1)
    spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.gridLayout.addItem(spacerItem, 21, 1, 1, 1)
    self.labelAfterTask = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAfterTask.sizePolicy().hasHeightForWidth())
    self.labelAfterTask.setSizePolicy(sizePolicy)
    self.labelAfterTask.setObjectName(_fromUtf8("labelAfterTask"))
    self.gridLayout.addWidget(self.labelAfterTask, 13, 0, 1, 1)
    self.lineEditLayer = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditLayer.sizePolicy().hasHeightForWidth())
    self.lineEditLayer.setSizePolicy(sizePolicy)
    self.lineEditLayer.setToolTip(_fromUtf8(""))
    self.lineEditLayer.setObjectName(_fromUtf8("lineEditLayer"))
    self.gridLayout.addWidget(self.lineEditLayer, 11, 1, 1, 1)
    self.comboBatching = QtGui.QComboBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboBatching.sizePolicy().hasHeightForWidth())
    self.comboBatching.setSizePolicy(sizePolicy)
    self.comboBatching.setObjectName(_fromUtf8("comboBatching"))
    self.comboBatching.addItem(_fromUtf8(""))
    self.comboBatching.addItem(_fromUtf8(""))
    self.gridLayout.addWidget(self.comboBatching, 17, 1, 1, 1)
    self.spinMaxBatch = QtGui.QSpinBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.spinMaxBatch.sizePolicy().hasHeightForWidth())
    self.spinMaxBatch.setSizePolicy(sizePolicy)
    self.spinMaxBatch.setMinimum(1)
    self.spinMaxBatch.setMaximum(999999999)
    self.spinMaxBatch.setObjectName(_fromUtf8("spinMaxBatch"))
    self.gridLayout.addWidget(self.spinMaxBatch, 19, 1, 1, 1)
    self.lineEditImageType = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditImageType.sizePolicy().hasHeightForWidth())
    self.lineEditImageType.setSizePolicy(sizePolicy)
    self.lineEditImageType.setToolTip(_fromUtf8(""))
    self.lineEditImageType.setObjectName(_fromUtf8("lineEditImageType"))
    self.gridLayout.addWidget(self.lineEditImageType, 3, 1, 1, 1)
    self.labelFileName = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelFileName.sizePolicy().hasHeightForWidth())
    self.labelFileName.setSizePolicy(sizePolicy)
    self.labelFileName.setObjectName(_fromUtf8("labelFileName"))
    self.gridLayout.addWidget(self.labelFileName, 0, 0, 1, 1)
    self.comboRenderer = QtGui.QComboBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboRenderer.sizePolicy().hasHeightForWidth())
    self.comboRenderer.setSizePolicy(sizePolicy)
    self.comboRenderer.setObjectName(_fromUtf8("comboRenderer"))
    self.gridLayout.addWidget(self.comboRenderer, 9, 1, 1, 1)
    self.lineEditCameras = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditCameras.sizePolicy().hasHeightForWidth())
    self.lineEditCameras.setSizePolicy(sizePolicy)
    self.lineEditCameras.setObjectName(_fromUtf8("lineEditCameras"))
    self.gridLayout.addWidget(self.lineEditCameras, 5, 1, 1, 1)
    self.labeFileType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labeFileType.sizePolicy().hasHeightForWidth())
    self.labeFileType.setSizePolicy(sizePolicy)
    self.labeFileType.setObjectName(_fromUtf8("labeFileType"))
    self.gridLayout.addWidget(self.labeFileType, 8, 0, 1, 1)
    self.comboHostGroup = QtGui.QComboBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboHostGroup.sizePolicy().hasHeightForWidth())
    self.comboHostGroup.setSizePolicy(sizePolicy)
    self.comboHostGroup.setObjectName(_fromUtf8("comboHostGroup"))
    self.gridLayout.addWidget(self.comboHostGroup, 7, 1, 1, 1)
    self.lineEditAfterTask = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditAfterTask.sizePolicy().hasHeightForWidth())
    self.lineEditAfterTask.setSizePolicy(sizePolicy)
    self.lineEditAfterTask.setObjectName(_fromUtf8("lineEditAfterTask"))
    self.gridLayout.addWidget(self.lineEditAfterTask, 13, 1, 1, 1)
    self.comboFileType = QtGui.QComboBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboFileType.sizePolicy().hasHeightForWidth())
    self.comboFileType.setSizePolicy(sizePolicy)
    self.comboFileType.setObjectName(_fromUtf8("comboFileType"))
    self.gridLayout.addWidget(self.comboFileType, 8, 1, 1, 1)
    self.lineEditResolution = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditResolution.sizePolicy().hasHeightForWidth())
    self.lineEditResolution.setSizePolicy(sizePolicy)
    self.lineEditResolution.setObjectName(_fromUtf8("lineEditResolution"))
    self.gridLayout.addWidget(self.lineEditResolution, 6, 1, 1, 1)
    self.labelResolution = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelResolution.sizePolicy().hasHeightForWidth())
    self.labelResolution.setSizePolicy(sizePolicy)
    self.labelResolution.setObjectName(_fromUtf8("labelResolution"))
    self.gridLayout.addWidget(self.labelResolution, 6, 0, 1, 1)
    self.lineEditFileName = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditFileName.sizePolicy().hasHeightForWidth())
    self.lineEditFileName.setSizePolicy(sizePolicy)
    self.lineEditFileName.setToolTip(_fromUtf8(""))
    self.lineEditFileName.setDragEnabled(True)
    self.lineEditFileName.setObjectName(_fromUtf8("lineEditFileName"))
    self.gridLayout.addWidget(self.lineEditFileName, 0, 1, 1, 1)
    self.labelFrange = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelFrange.sizePolicy().hasHeightForWidth())
    self.labelFrange.setSizePolicy(sizePolicy)
    self.labelFrange.setObjectName(_fromUtf8("labelFrange"))
    self.gridLayout.addWidget(self.labelFrange, 4, 0, 1, 1)
    self.lineEditFrange = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditFrange.sizePolicy().hasHeightForWidth())
    self.lineEditFrange.setSizePolicy(sizePolicy)
    self.lineEditFrange.setToolTip(_fromUtf8(""))
    self.lineEditFrange.setObjectName(_fromUtf8("lineEditFrange"))
    self.gridLayout.addWidget(self.lineEditFrange, 4, 1, 1, 1)
    self.labelCamera = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelCamera.sizePolicy().hasHeightForWidth())
    self.labelCamera.setSizePolicy(sizePolicy)
    self.labelCamera.setObjectName(_fromUtf8("labelCamera"))
    self.gridLayout.addWidget(self.labelCamera, 5, 0, 1, 1)
    self.pushSubmit = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushSubmit.sizePolicy().hasHeightForWidth())
    self.pushSubmit.setSizePolicy(sizePolicy)
    self.pushSubmit.setObjectName(_fromUtf8("pushSubmit"))
    self.gridLayout.addWidget(self.pushSubmit, 21, 2, 1, 1)
    self.lineEditDescription = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditDescription.sizePolicy().hasHeightForWidth())
    self.lineEditDescription.setSizePolicy(sizePolicy)
    self.lineEditDescription.setDragEnabled(True)
    self.lineEditDescription.setObjectName(_fromUtf8("lineEditDescription"))
    self.gridLayout.addWidget(self.lineEditDescription, 20, 1, 1, 1)
    self.comboOsType = QtGui.QComboBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboOsType.sizePolicy().hasHeightForWidth())
    self.comboOsType.setSizePolicy(sizePolicy)
    self.comboOsType.setObjectName(_fromUtf8("comboOsType"))
    self.gridLayout.addWidget(self.comboOsType, 12, 1, 1, 1)
    self.labelBatching = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelBatching.sizePolicy().hasHeightForWidth())
    self.labelBatching.setSizePolicy(sizePolicy)
    self.labelBatching.setObjectName(_fromUtf8("labelBatching"))
    self.gridLayout.addWidget(self.labelBatching, 17, 0, 1, 1)
    self.labelPrio = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelPrio.sizePolicy().hasHeightForWidth())
    self.labelPrio.setSizePolicy(sizePolicy)
    self.labelPrio.setObjectName(_fromUtf8("labelPrio"))
    self.gridLayout.addWidget(self.labelPrio, 15, 0, 1, 1)
    self.pushOutDir = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushOutDir.sizePolicy().hasHeightForWidth())
    self.pushOutDir.setSizePolicy(sizePolicy)
    self.pushOutDir.setObjectName(_fromUtf8("pushOutDir"))
    self.gridLayout.addWidget(self.pushOutDir, 1, 2, 1, 1)
    self.lineEditOutName = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditOutName.sizePolicy().hasHeightForWidth())
    self.lineEditOutName.setSizePolicy(sizePolicy)
    self.lineEditOutName.setDragEnabled(True)
    self.lineEditOutName.setObjectName(_fromUtf8("lineEditOutName"))
    self.gridLayout.addWidget(self.lineEditOutName, 2, 1, 1, 1)
    self.labelAfterTime = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAfterTime.sizePolicy().hasHeightForWidth())
    self.labelAfterTime.setSizePolicy(sizePolicy)
    self.labelAfterTime.setObjectName(_fromUtf8("labelAfterTime"))
    self.gridLayout.addWidget(self.labelAfterTime, 14, 0, 1, 1)
    self.afterTimeEdit = QtGui.QDateTimeEdit(self.centralwidget)
    self.afterTimeEdit.setEnabled(False)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.afterTimeEdit.sizePolicy().hasHeightForWidth())
    self.afterTimeEdit.setSizePolicy(sizePolicy)
    self.afterTimeEdit.setTime(QtCore.QTime(14, 0, 0))
    self.afterTimeEdit.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
    self.afterTimeEdit.setCalendarPopup(True)
    self.afterTimeEdit.setObjectName(_fromUtf8("afterTimeEdit"))
    self.gridLayout.addWidget(self.afterTimeEdit, 14, 1, 1, 1)
    self.checkAfterTime = QtGui.QCheckBox(self.centralwidget)
    self.checkAfterTime.setObjectName(_fromUtf8("checkAfterTime"))
    self.gridLayout.addWidget(self.checkAfterTime, 14, 2, 1, 1)
    rbhusSubmit.setCentralWidget(self.centralwidget)
    self.menubar = QtGui.QMenuBar(rbhusSubmit)
    self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 19))
    self.menubar.setObjectName(_fromUtf8("menubar"))
    rbhusSubmit.setMenuBar(self.menubar)

    self.retranslateUi(rbhusSubmit)
    QtCore.QMetaObject.connectSlotsByName(rbhusSubmit)

  def retranslateUi(self, rbhusSubmit):
    rbhusSubmit.setWindowTitle(_translate("rbhusSubmit", "rbhusSubmit", None))
    self.labelOsType.setText(_translate("rbhusSubmit", "osType", None))
    self.comboPrio.setItemText(0, _translate("rbhusSubmit", "low", None))
    self.comboPrio.setItemText(1, _translate("rbhusSubmit", "normal", None))
    self.comboPrio.setItemText(2, _translate("rbhusSubmit", "high", None))
    self.labelMinBatch.setText(_translate("rbhusSubmit", "minBatch", None))
    self.labelImageType.setText(_translate("rbhusSubmit", "imageType", None))
    self.labelImageName.setText(_translate("rbhusSubmit", "outName", None))
    self.labelMaxBatch.setText(_translate("rbhusSubmit", "maxBatch", None))
    self.labelLayer.setText(_translate("rbhusSubmit", "layer", None))
    self.pushFileName.setText(_translate("rbhusSubmit", "open", None))
    self.labeRenderer.setText(_translate("rbhusSubmit", "renderer", None))
    self.lineEditOutDir.setWhatsThis(_translate("rbhusSubmit", "output directory to dump files", None))
    self.lineEditOutDir.setText(_translate("rbhusSubmit", "default", None))
    self.labelDescription.setText(_translate("rbhusSubmit", "description", None))
    self.labelHostGroup.setText(_translate("rbhusSubmit", "hostGroup", None))
    self.labelOutDir.setText(_translate("rbhusSubmit", "outDir", None))
    self.labelAfterTask.setText(_translate("rbhusSubmit", "afterTasks", None))
    self.lineEditLayer.setText(_translate("rbhusSubmit", "default", None))
    self.comboBatching.setItemText(0, _translate("rbhusSubmit", "deactive", None))
    self.comboBatching.setItemText(1, _translate("rbhusSubmit", "active", None))
    self.lineEditImageType.setWhatsThis(_translate("rbhusSubmit", "<html><head/><body><p>type of image. </p><p>eg: PNG, MULTIEXR etc . </p><p><span style=\" font-style:italic; text-decoration: underline;\">note : image type depends on the command line interface of the program</span></p></body></html>", None))
    self.lineEditImageType.setText(_translate("rbhusSubmit", "default", None))
    self.labelFileName.setText(_translate("rbhusSubmit", "fileName", None))
    self.lineEditCameras.setToolTip(_translate("rbhusSubmit", "comma seperated list of cameras to render", None))
    self.lineEditCameras.setText(_translate("rbhusSubmit", "default", None))
    self.labeFileType.setText(_translate("rbhusSubmit", "fileType", None))
    self.lineEditAfterTask.setText(_translate("rbhusSubmit", "0", None))
    self.lineEditResolution.setToolTip(_translate("rbhusSubmit", "resolution of the output", None))
    self.lineEditResolution.setText(_translate("rbhusSubmit", "default", None))
    self.labelResolution.setText(_translate("rbhusSubmit", "resolution", None))
    self.lineEditFileName.setWhatsThis(_translate("rbhusSubmit", "comma seperated list of files to render", None))
    self.labelFrange.setText(_translate("rbhusSubmit", "fRange     ", None))
    self.lineEditFrange.setWhatsThis(_translate("rbhusSubmit", "<html><head/><body><p>frame range in the format</p><p>startframe-endframe:byframes</p><p>eg:</p><p>render frames from 1 to 100   : <span style=\" font-weight:600;\">1-100</span></p><p>render every 5th frame from 1 to 100   : <span style=\" font-weight:600;\">1-100:5</span></p><p>render 1 frame     :<span style=\" font-weight:600;\"> 1</span></p><p><br/></p><p><br/></p></body></html>", None))
    self.lineEditFrange.setText(_translate("rbhusSubmit", "1", None))
    self.labelCamera.setText(_translate("rbhusSubmit", "cameras", None))
    self.pushSubmit.setText(_translate("rbhusSubmit", "submit", None))
    self.lineEditDescription.setText(_translate("rbhusSubmit", "default", None))
    self.labelBatching.setText(_translate("rbhusSubmit", "batching", None))
    self.labelPrio.setText(_translate("rbhusSubmit", "priority", None))
    self.pushOutDir.setText(_translate("rbhusSubmit", "open", None))
    self.lineEditOutName.setToolTip(_translate("rbhusSubmit", "name of the image file. eg: wtf.png", None))
    self.lineEditOutName.setWhatsThis(_translate("rbhusSubmit", "<html><head/><body><p>name of the image file. eg: <span style=\" font-weight:600;\">wtfigo.png</span></p></body></html>", None))
    self.lineEditOutName.setText(_translate("rbhusSubmit", "default", None))
    self.labelAfterTime.setText(_translate("rbhusSubmit", "afterTime ", None))
    self.afterTimeEdit.setDisplayFormat(_translate("rbhusSubmit", "yyyy-M-d h:mm A", None))
    self.checkAfterTime.setText(_translate("rbhusSubmit", "enable", None))

