# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusHostMod.ui'
#
# Created: Tue Oct  8 13:41:19 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(813, 356)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
    MainWindow.setSizePolicy(sizePolicy)
    MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.centralwidget = QtGui.QWidget(MainWindow)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
    self.centralwidget.setSizePolicy(sizePolicy)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.horizontalLayout_2 = QtGui.QHBoxLayout()
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    self.pushLocalStop = QtGui.QPushButton(self.centralwidget)
    palette = QtGui.QPalette()
    brush = QtGui.QBrush(QtGui.QColor(237, 114, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
    brush = QtGui.QBrush(QtGui.QColor(237, 114, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
    brush = QtGui.QBrush(QtGui.QColor(237, 114, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
    self.pushLocalStop.setPalette(palette)
    font = QtGui.QFont()
    font.setFamily(_fromUtf8("Sans Serif"))
    font.setPointSize(10)
    font.setKerning(True)
    self.pushLocalStop.setFont(font)
    self.pushLocalStop.setAutoFillBackground(False)
    self.pushLocalStop.setIconSize(QtCore.QSize(16, 16))
    self.pushLocalStop.setFlat(False)
    self.pushLocalStop.setObjectName(_fromUtf8("pushLocalStop"))
    self.horizontalLayout_2.addWidget(self.pushLocalStop)
    self.pushLocalEnable = QtGui.QPushButton(self.centralwidget)
    palette = QtGui.QPalette()
    brush = QtGui.QBrush(QtGui.QColor(90, 223, 1))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
    brush = QtGui.QBrush(QtGui.QColor(90, 223, 1))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
    brush = QtGui.QBrush(QtGui.QColor(90, 223, 1))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
    brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
    self.pushLocalEnable.setPalette(palette)
    font = QtGui.QFont()
    font.setFamily(_fromUtf8("Sans Serif"))
    font.setPointSize(10)
    font.setKerning(True)
    self.pushLocalEnable.setFont(font)
    self.pushLocalEnable.setAutoFillBackground(False)
    self.pushLocalEnable.setIconSize(QtCore.QSize(16, 16))
    self.pushLocalEnable.setFlat(False)
    self.pushLocalEnable.setObjectName(_fromUtf8("pushLocalEnable"))
    self.horizontalLayout_2.addWidget(self.pushLocalEnable)
    spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout_2.addItem(spacerItem)
    self.pushRefresh = QtGui.QPushButton(self.centralwidget)
    self.pushRefresh.setObjectName(_fromUtf8("pushRefresh"))
    self.horizontalLayout_2.addWidget(self.pushRefresh)
    self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 2)
    self.tableHost = QtGui.QTableWidget(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tableHost.sizePolicy().hasHeightForWidth())
    self.tableHost.setSizePolicy(sizePolicy)
    self.tableHost.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
    self.tableHost.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.tableHost.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
    self.tableHost.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
    self.tableHost.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
    self.tableHost.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
    self.tableHost.setObjectName(_fromUtf8("tableHost"))
    self.tableHost.setColumnCount(0)
    self.tableHost.setRowCount(0)
    self.tableHost.horizontalHeader().setCascadingSectionResizes(True)
    self.tableHost.horizontalHeader().setStretchLastSection(True)
    self.tableHost.verticalHeader().setStretchLastSection(False)
    self.gridLayout.addWidget(self.tableHost, 4, 0, 1, 1)
    self.horizontalLayout = QtGui.QHBoxLayout()
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.LabelTotal = QtGui.QLabel(self.centralwidget)
    self.LabelTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.LabelTotal.setObjectName(_fromUtf8("LabelTotal"))
    self.horizontalLayout.addWidget(self.LabelTotal)
    spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem1)
    self.LabelRunning = QtGui.QLabel(self.centralwidget)
    self.LabelRunning.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.LabelRunning.setObjectName(_fromUtf8("LabelRunning"))
    self.horizontalLayout.addWidget(self.LabelRunning)
    self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
    MainWindow.setCentralWidget(self.centralwidget)

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(_translate("MainWindow", "rbhusHost", None))
    self.pushLocalStop.setText(_translate("MainWindow", "STOP MY HOST", None))
    self.pushLocalEnable.setText(_translate("MainWindow", "ENABLE MY HOST", None))
    self.pushRefresh.setText(_translate("MainWindow", "refresh", None))
    self.tableHost.setSortingEnabled(True)
    self.LabelTotal.setText(_translate("MainWindow", "total : 3", None))
    self.LabelRunning.setText(_translate("MainWindow", "running : 3", None))

