# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusHostEditMod.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rbhusHostEdit(object):
    def setupUi(self, rbhusHostEdit):
        rbhusHostEdit.setObjectName("rbhusHostEdit")
        rbhusHostEdit.resize(503, 97)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rbhusHostEdit.sizePolicy().hasHeightForWidth())
        rbhusHostEdit.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(rbhusHostEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.labelImageName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImageName.sizePolicy().hasHeightForWidth())
        self.labelImageName.setSizePolicy(sizePolicy)
        self.labelImageName.setObjectName("labelImageName")
        self.gridLayout.addWidget(self.labelImageName, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushApply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushApply.sizePolicy().hasHeightForWidth())
        self.pushApply.setSizePolicy(sizePolicy)
        self.pushApply.setObjectName("pushApply")
        self.horizontalLayout.addWidget(self.pushApply)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 2)
        self.spinCpu = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCpu.sizePolicy().hasHeightForWidth())
        self.spinCpu.setSizePolicy(sizePolicy)
        self.spinCpu.setObjectName("spinCpu")
        self.gridLayout.addWidget(self.spinCpu, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditGroups = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditGroups.setObjectName("lineEditGroups")
        self.gridLayout.addWidget(self.lineEditGroups, 1, 1, 1, 1)
        self.pushReset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushReset.sizePolicy().hasHeightForWidth())
        self.pushReset.setSizePolicy(sizePolicy)
        self.pushReset.setObjectName("pushReset")
        self.gridLayout.addWidget(self.pushReset, 2, 0, 1, 1)
        self.pushSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushSelect.setObjectName("pushSelect")
        self.gridLayout.addWidget(self.pushSelect, 1, 2, 1, 1)
        rbhusHostEdit.setCentralWidget(self.centralwidget)

        self.retranslateUi(rbhusHostEdit)
        QtCore.QMetaObject.connectSlotsByName(rbhusHostEdit)

    def retranslateUi(self, rbhusHostEdit):
        _translate = QtCore.QCoreApplication.translate
        rbhusHostEdit.setWindowTitle(_translate("rbhusHostEdit", "rbhusHostEdit"))
        self.labelImageName.setToolTip(_translate("rbhusHostEdit", "Effective Number of Cores to use for render"))
        self.labelImageName.setText(_translate("rbhusHostEdit", "eCpus"))
        self.pushApply.setText(_translate("rbhusHostEdit", "apply"))
        self.label.setText(_translate("rbhusHostEdit", "groups"))
        self.pushReset.setText(_translate("rbhusHostEdit", "reset"))
        self.pushSelect.setText(_translate("rbhusHostEdit", "select"))
