# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusAuthMod.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowAuth(object):
    def setupUi(self, MainWindowAuth):
        MainWindowAuth.setObjectName("MainWindowAuth")
        MainWindowAuth.setWindowModality(QtCore.Qt.WindowModal)
        MainWindowAuth.resize(294, 116)
        self.centralwidget = QtWidgets.QWidget(MainWindowAuth)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelUser = QtWidgets.QLabel(self.centralwidget)
        self.labelUser.setEnabled(True)
        self.labelUser.setObjectName("labelUser")
        self.gridLayout.addWidget(self.labelUser, 0, 0, 1, 1)
        self.lineEditUser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUser.setObjectName("lineEditUser")
        self.gridLayout.addWidget(self.lineEditUser, 0, 1, 1, 1)
        self.labelPass = QtWidgets.QLabel(self.centralwidget)
        self.labelPass.setObjectName("labelPass")
        self.gridLayout.addWidget(self.labelPass, 1, 0, 1, 1)
        self.lineEditPass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPass.setObjectName("lineEditPass")
        self.gridLayout.addWidget(self.lineEditPass, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxRememberMe = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRememberMe.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBoxRememberMe.setChecked(True)
        self.checkBoxRememberMe.setObjectName("checkBoxRememberMe")
        self.horizontalLayout_3.addWidget(self.checkBoxRememberMe)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindowAuth.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowAuth)
        QtCore.QMetaObject.connectSlotsByName(MainWindowAuth)

    def retranslateUi(self, MainWindowAuth):
        _translate = QtCore.QCoreApplication.translate
        MainWindowAuth.setWindowTitle(_translate("MainWindowAuth", "login"))
        self.labelUser.setText(_translate("MainWindowAuth", "username"))
        self.labelPass.setText(_translate("MainWindowAuth", "password"))
        self.checkBoxRememberMe.setText(_translate("MainWindowAuth", "rememberMe"))
        self.pushButton.setText(_translate("MainWindowAuth", "login"))
        self.pushButton.setShortcut(_translate("MainWindowAuth", "Return"))
