# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusSubmitMod.ui'
#
# Created: Wed Nov  7 21:35:09 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_rbhusSubmit(object):
    def setupUi(self, rbhusSubmit):
        rbhusSubmit.setObjectName(_fromUtf8("rbhusSubmit"))
        rbhusSubmit.resize(724, 525)
        self.centralwidget = QtGui.QWidget(rbhusSubmit)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelAfterTask = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAfterTask.sizePolicy().hasHeightForWidth())
        self.labelAfterTask.setSizePolicy(sizePolicy)
        self.labelAfterTask.setObjectName(_fromUtf8("labelAfterTask"))
        self.gridLayout.addWidget(self.labelAfterTask, 12, 0, 1, 1)
        self.comboFileType = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFileType.sizePolicy().hasHeightForWidth())
        self.comboFileType.setSizePolicy(sizePolicy)
        self.comboFileType.setObjectName(_fromUtf8("comboFileType"))
        self.gridLayout.addWidget(self.comboFileType, 7, 2, 1, 1)
        self.pushFileName = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushFileName.sizePolicy().hasHeightForWidth())
        self.pushFileName.setSizePolicy(sizePolicy)
        self.pushFileName.setObjectName(_fromUtf8("pushFileName"))
        self.gridLayout.addWidget(self.pushFileName, 0, 5, 1, 1)
        self.labelPrio = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPrio.sizePolicy().hasHeightForWidth())
        self.labelPrio.setSizePolicy(sizePolicy)
        self.labelPrio.setObjectName(_fromUtf8("labelPrio"))
        self.gridLayout.addWidget(self.labelPrio, 13, 0, 1, 1)
        self.labeFileType = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labeFileType.sizePolicy().hasHeightForWidth())
        self.labeFileType.setSizePolicy(sizePolicy)
        self.labeFileType.setObjectName(_fromUtf8("labeFileType"))
        self.gridLayout.addWidget(self.labeFileType, 7, 0, 1, 1)
        self.pushSubmit = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushSubmit.sizePolicy().hasHeightForWidth())
        self.pushSubmit.setSizePolicy(sizePolicy)
        self.pushSubmit.setObjectName(_fromUtf8("pushSubmit"))
        self.gridLayout.addWidget(self.pushSubmit, 15, 5, 1, 1)
        self.labeRenderer = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labeRenderer.sizePolicy().hasHeightForWidth())
        self.labeRenderer.setSizePolicy(sizePolicy)
        self.labeRenderer.setObjectName(_fromUtf8("labeRenderer"))
        self.gridLayout.addWidget(self.labeRenderer, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 15, 2, 1, 1)
        self.comboPrio = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPrio.sizePolicy().hasHeightForWidth())
        self.comboPrio.setSizePolicy(sizePolicy)
        self.comboPrio.setObjectName(_fromUtf8("comboPrio"))
        self.comboPrio.addItem(_fromUtf8(""))
        self.comboPrio.addItem(_fromUtf8(""))
        self.comboPrio.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboPrio, 13, 2, 1, 1)
        self.lineEditAfterTask = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAfterTask.sizePolicy().hasHeightForWidth())
        self.lineEditAfterTask.setSizePolicy(sizePolicy)
        self.lineEditAfterTask.setObjectName(_fromUtf8("lineEditAfterTask"))
        self.gridLayout.addWidget(self.lineEditAfterTask, 12, 2, 1, 1)
        self.lineEditLayer = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLayer.sizePolicy().hasHeightForWidth())
        self.lineEditLayer.setSizePolicy(sizePolicy)
        self.lineEditLayer.setObjectName(_fromUtf8("lineEditLayer"))
        self.gridLayout.addWidget(self.lineEditLayer, 10, 2, 1, 1)
        self.lineEditFrange = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFrange.sizePolicy().hasHeightForWidth())
        self.lineEditFrange.setSizePolicy(sizePolicy)
        self.lineEditFrange.setObjectName(_fromUtf8("lineEditFrange"))
        self.gridLayout.addWidget(self.lineEditFrange, 4, 2, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.textEdit.setLineWidth(1)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 16, 0, 1, 6)
        self.labelFrange = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFrange.sizePolicy().hasHeightForWidth())
        self.labelFrange.setSizePolicy(sizePolicy)
        self.labelFrange.setObjectName(_fromUtf8("labelFrange"))
        self.gridLayout.addWidget(self.labelFrange, 4, 0, 1, 1)
        self.labelFileName = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFileName.sizePolicy().hasHeightForWidth())
        self.labelFileName.setSizePolicy(sizePolicy)
        self.labelFileName.setObjectName(_fromUtf8("labelFileName"))
        self.gridLayout.addWidget(self.labelFileName, 0, 0, 1, 1)
        self.comboOsType = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboOsType.sizePolicy().hasHeightForWidth())
        self.comboOsType.setSizePolicy(sizePolicy)
        self.comboOsType.setObjectName(_fromUtf8("comboOsType"))
        self.gridLayout.addWidget(self.comboOsType, 11, 2, 1, 1)
        self.labelOsType = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOsType.sizePolicy().hasHeightForWidth())
        self.labelOsType.setSizePolicy(sizePolicy)
        self.labelOsType.setObjectName(_fromUtf8("labelOsType"))
        self.gridLayout.addWidget(self.labelOsType, 11, 0, 1, 1)
        self.comboRenderer = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboRenderer.sizePolicy().hasHeightForWidth())
        self.comboRenderer.setSizePolicy(sizePolicy)
        self.comboRenderer.setObjectName(_fromUtf8("comboRenderer"))
        self.gridLayout.addWidget(self.comboRenderer, 8, 2, 1, 1)
        self.labelHostGroup = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHostGroup.sizePolicy().hasHeightForWidth())
        self.labelHostGroup.setSizePolicy(sizePolicy)
        self.labelHostGroup.setObjectName(_fromUtf8("labelHostGroup"))
        self.gridLayout.addWidget(self.labelHostGroup, 6, 0, 1, 1)
        self.labelLayer = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLayer.sizePolicy().hasHeightForWidth())
        self.labelLayer.setSizePolicy(sizePolicy)
        self.labelLayer.setObjectName(_fromUtf8("labelLayer"))
        self.gridLayout.addWidget(self.labelLayer, 10, 0, 1, 1)
        self.comboHostGroup = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboHostGroup.sizePolicy().hasHeightForWidth())
        self.comboHostGroup.setSizePolicy(sizePolicy)
        self.comboHostGroup.setObjectName(_fromUtf8("comboHostGroup"))
        self.gridLayout.addWidget(self.comboHostGroup, 6, 2, 1, 1)
        self.labelOutDir = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOutDir.sizePolicy().hasHeightForWidth())
        self.labelOutDir.setSizePolicy(sizePolicy)
        self.labelOutDir.setObjectName(_fromUtf8("labelOutDir"))
        self.gridLayout.addWidget(self.labelOutDir, 1, 0, 1, 1)
        self.lineEditOutDir = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOutDir.sizePolicy().hasHeightForWidth())
        self.lineEditOutDir.setSizePolicy(sizePolicy)
        self.lineEditOutDir.setDragEnabled(True)
        self.lineEditOutDir.setObjectName(_fromUtf8("lineEditOutDir"))
        self.gridLayout.addWidget(self.lineEditOutDir, 1, 2, 1, 1)
        self.labelImageName = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImageName.sizePolicy().hasHeightForWidth())
        self.labelImageName.setSizePolicy(sizePolicy)
        self.labelImageName.setObjectName(_fromUtf8("labelImageName"))
        self.gridLayout.addWidget(self.labelImageName, 2, 0, 1, 1)
        self.lineEditOutName = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOutName.sizePolicy().hasHeightForWidth())
        self.lineEditOutName.setSizePolicy(sizePolicy)
        self.lineEditOutName.setDragEnabled(True)
        self.lineEditOutName.setObjectName(_fromUtf8("lineEditOutName"))
        self.gridLayout.addWidget(self.lineEditOutName, 2, 2, 1, 1)
        self.labelImageType = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImageType.sizePolicy().hasHeightForWidth())
        self.labelImageType.setSizePolicy(sizePolicy)
        self.labelImageType.setObjectName(_fromUtf8("labelImageType"))
        self.gridLayout.addWidget(self.labelImageType, 3, 0, 1, 1)
        self.lineEditImageType = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditImageType.sizePolicy().hasHeightForWidth())
        self.lineEditImageType.setSizePolicy(sizePolicy)
        self.lineEditImageType.setObjectName(_fromUtf8("lineEditImageType"))
        self.gridLayout.addWidget(self.lineEditImageType, 3, 2, 1, 1)
        self.lineEditFileName = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFileName.sizePolicy().hasHeightForWidth())
        self.lineEditFileName.setSizePolicy(sizePolicy)
        self.lineEditFileName.setDragEnabled(True)
        self.lineEditFileName.setObjectName(_fromUtf8("lineEditFileName"))
        self.gridLayout.addWidget(self.lineEditFileName, 0, 2, 1, 1)
        self.pushOutDir = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushOutDir.sizePolicy().hasHeightForWidth())
        self.pushOutDir.setSizePolicy(sizePolicy)
        self.pushOutDir.setObjectName(_fromUtf8("pushOutDir"))
        self.gridLayout.addWidget(self.pushOutDir, 1, 5, 1, 1)
        rbhusSubmit.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(rbhusSubmit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        rbhusSubmit.setMenuBar(self.menubar)

        self.retranslateUi(rbhusSubmit)
        QtCore.QMetaObject.connectSlotsByName(rbhusSubmit)

    def retranslateUi(self, rbhusSubmit):
        rbhusSubmit.setWindowTitle(QtGui.QApplication.translate("rbhusSubmit", "rbhusSubmit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAfterTask.setText(QtGui.QApplication.translate("rbhusSubmit", "afterTasks", None, QtGui.QApplication.UnicodeUTF8))
        self.pushFileName.setText(QtGui.QApplication.translate("rbhusSubmit", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPrio.setText(QtGui.QApplication.translate("rbhusSubmit", "priority", None, QtGui.QApplication.UnicodeUTF8))
        self.labeFileType.setText(QtGui.QApplication.translate("rbhusSubmit", "fileType", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSubmit.setText(QtGui.QApplication.translate("rbhusSubmit", "submit", None, QtGui.QApplication.UnicodeUTF8))
        self.labeRenderer.setText(QtGui.QApplication.translate("rbhusSubmit", "renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(0, QtGui.QApplication.translate("rbhusSubmit", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(1, QtGui.QApplication.translate("rbhusSubmit", "normal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboPrio.setItemText(2, QtGui.QApplication.translate("rbhusSubmit", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditAfterTask.setText(QtGui.QApplication.translate("rbhusSubmit", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditLayer.setText(QtGui.QApplication.translate("rbhusSubmit", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("rbhusSubmit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:normal; color:#c00000;\">--HELP--</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">bfc : beforeFrameCmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">       These commands run before a frame starts</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">afc : afterFrameCmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">       These commands run after a frame completes</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:normal;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">fRange : Frame Range</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">             start-end:byframes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">             eg: if we want every 5th frame to render from 1 to 300 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">                   we can input 1-300:5 , </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">             </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFrange.setText(QtGui.QApplication.translate("rbhusSubmit", "fRange     ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFileName.setText(QtGui.QApplication.translate("rbhusSubmit", "fileName", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOsType.setText(QtGui.QApplication.translate("rbhusSubmit", "osType", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHostGroup.setText(QtGui.QApplication.translate("rbhusSubmit", "hostGroup", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLayer.setText(QtGui.QApplication.translate("rbhusSubmit", "layer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutDir.setText(QtGui.QApplication.translate("rbhusSubmit", "outDir", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOutDir.setText(QtGui.QApplication.translate("rbhusSubmit", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImageName.setText(QtGui.QApplication.translate("rbhusSubmit", "outName", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOutName.setText(QtGui.QApplication.translate("rbhusSubmit", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImageType.setText(QtGui.QApplication.translate("rbhusSubmit", "imageType", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditImageType.setText(QtGui.QApplication.translate("rbhusSubmit", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.pushOutDir.setText(QtGui.QApplication.translate("rbhusSubmit", "open", None, QtGui.QApplication.UnicodeUTF8))

