# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusPipeAssetCreateMod_new.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1606101416
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(500, 628)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.labelAssName = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAssName.sizePolicy().hasHeightForWidth())
    self.labelAssName.setSizePolicy(sizePolicy)
    self.labelAssName.setObjectName(_fromUtf8("labelAssName"))
    self.gridLayout.addWidget(self.labelAssName, 0, 0, 1, 1)
    self.horizontalLayout = QtGui.QHBoxLayout()
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.lineEditAssName = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditAssName.sizePolicy().hasHeightForWidth())
    self.lineEditAssName.setSizePolicy(sizePolicy)
    self.lineEditAssName.setObjectName(_fromUtf8("lineEditAssName"))
    self.horizontalLayout.addWidget(self.lineEditAssName)
    self.pushAssets = QtGui.QPushButton(self.centralwidget)
    self.pushAssets.setEnabled(False)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushAssets.sizePolicy().hasHeightForWidth())
    self.pushAssets.setSizePolicy(sizePolicy)
    self.pushAssets.setObjectName(_fromUtf8("pushAssets"))
    self.horizontalLayout.addWidget(self.pushAssets)
    self.checkAssName = QtGui.QCheckBox(self.centralwidget)
    self.checkAssName.setEnabled(True)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkAssName.sizePolicy().hasHeightForWidth())
    self.checkAssName.setSizePolicy(sizePolicy)
    self.checkAssName.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.checkAssName.setText(_fromUtf8(""))
    self.checkAssName.setChecked(False)
    self.checkAssName.setObjectName(_fromUtf8("checkAssName"))
    self.horizontalLayout.addWidget(self.checkAssName)
    self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
    self.labelAssType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAssType.sizePolicy().hasHeightForWidth())
    self.labelAssType.setSizePolicy(sizePolicy)
    self.labelAssType.setObjectName(_fromUtf8("labelAssType"))
    self.gridLayout.addWidget(self.labelAssType, 1, 0, 1, 1)
    self.horizontalLayout_3 = QtGui.QHBoxLayout()
    self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
    self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
    self.labelDirectory = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDirectory.sizePolicy().hasHeightForWidth())
    self.labelDirectory.setSizePolicy(sizePolicy)
    self.labelDirectory.setObjectName(_fromUtf8("labelDirectory"))
    self.gridLayout.addWidget(self.labelDirectory, 2, 0, 1, 1)
    self.horizontalLayout_2 = QtGui.QHBoxLayout()
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    self.comboDirectory = QtGui.QComboBox(self.centralwidget)
    self.comboDirectory.setObjectName(_fromUtf8("comboDirectory"))
    self.horizontalLayout_2.addWidget(self.comboDirectory)
    self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
    self.labelSequence = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelSequence.sizePolicy().hasHeightForWidth())
    self.labelSequence.setSizePolicy(sizePolicy)
    self.labelSequence.setObjectName(_fromUtf8("labelSequence"))
    self.gridLayout.addWidget(self.labelSequence, 3, 0, 1, 1)
    self.horizontalLayout_4 = QtGui.QHBoxLayout()
    self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
    self.comboSequence = QtGui.QComboBox(self.centralwidget)
    self.comboSequence.setObjectName(_fromUtf8("comboSequence"))
    self.horizontalLayout_4.addWidget(self.comboSequence)
    self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
    self.labelScene = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelScene.sizePolicy().hasHeightForWidth())
    self.labelScene.setSizePolicy(sizePolicy)
    self.labelScene.setObjectName(_fromUtf8("labelScene"))
    self.gridLayout.addWidget(self.labelScene, 4, 0, 1, 1)
    self.horizontalLayout_5 = QtGui.QHBoxLayout()
    self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
    self.pushScenes = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushScenes.sizePolicy().hasHeightForWidth())
    self.pushScenes.setSizePolicy(sizePolicy)
    self.pushScenes.setObjectName(_fromUtf8("pushScenes"))
    self.horizontalLayout_5.addWidget(self.pushScenes)
    self.lineEditScenes = QtGui.QLineEdit(self.centralwidget)
    self.lineEditScenes.setEnabled(False)
    self.lineEditScenes.setReadOnly(True)
    self.lineEditScenes.setObjectName(_fromUtf8("lineEditScenes"))
    self.horizontalLayout_5.addWidget(self.lineEditScenes)
    self.gridLayout.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
    self.labelStageType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelStageType.sizePolicy().hasHeightForWidth())
    self.labelStageType.setSizePolicy(sizePolicy)
    self.labelStageType.setObjectName(_fromUtf8("labelStageType"))
    self.gridLayout.addWidget(self.labelStageType, 5, 0, 1, 1)
    self.horizontalLayout_6 = QtGui.QHBoxLayout()
    self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
    self.comboStageType = QtGui.QComboBox(self.centralwidget)
    self.comboStageType.setObjectName(_fromUtf8("comboStageType"))
    self.horizontalLayout_6.addWidget(self.comboStageType)
    self.gridLayout.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
    self.labelNodeType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelNodeType.sizePolicy().hasHeightForWidth())
    self.labelNodeType.setSizePolicy(sizePolicy)
    self.labelNodeType.setObjectName(_fromUtf8("labelNodeType"))
    self.gridLayout.addWidget(self.labelNodeType, 6, 0, 1, 1)
    self.horizontalLayout_7 = QtGui.QHBoxLayout()
    self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
    self.pushNodes = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushNodes.sizePolicy().hasHeightForWidth())
    self.pushNodes.setSizePolicy(sizePolicy)
    self.pushNodes.setObjectName(_fromUtf8("pushNodes"))
    self.horizontalLayout_7.addWidget(self.pushNodes)
    self.lineEditNodes = QtGui.QLineEdit(self.centralwidget)
    self.lineEditNodes.setEnabled(False)
    self.lineEditNodes.setReadOnly(True)
    self.lineEditNodes.setObjectName(_fromUtf8("lineEditNodes"))
    self.horizontalLayout_7.addWidget(self.lineEditNodes)
    self.gridLayout.addLayout(self.horizontalLayout_7, 6, 1, 1, 1)
    self.labelFRange = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelFRange.sizePolicy().hasHeightForWidth())
    self.labelFRange.setSizePolicy(sizePolicy)
    self.labelFRange.setObjectName(_fromUtf8("labelFRange"))
    self.gridLayout.addWidget(self.labelFRange, 7, 0, 1, 1)
    self.horizontalLayout_8 = QtGui.QHBoxLayout()
    self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
    self.lineEditFRange = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditFRange.sizePolicy().hasHeightForWidth())
    self.lineEditFRange.setSizePolicy(sizePolicy)
    self.lineEditFRange.setObjectName(_fromUtf8("lineEditFRange"))
    self.horizontalLayout_8.addWidget(self.lineEditFRange)
    self.gridLayout.addLayout(self.horizontalLayout_8, 7, 1, 1, 1)
    self.labelDue = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDue.sizePolicy().hasHeightForWidth())
    self.labelDue.setSizePolicy(sizePolicy)
    self.labelDue.setObjectName(_fromUtf8("labelDue"))
    self.gridLayout.addWidget(self.labelDue, 8, 0, 1, 1)
    self.horizontalLayout_9 = QtGui.QHBoxLayout()
    self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
    self.dateEditDue = QtGui.QDateTimeEdit(self.centralwidget)
    self.dateEditDue.setCalendarPopup(True)
    self.dateEditDue.setObjectName(_fromUtf8("dateEditDue"))
    self.horizontalLayout_9.addWidget(self.dateEditDue)
    self.gridLayout.addLayout(self.horizontalLayout_9, 8, 1, 1, 1)
    self.labelAdmin = QtGui.QLabel(self.centralwidget)
    self.labelAdmin.setObjectName(_fromUtf8("labelAdmin"))
    self.gridLayout.addWidget(self.labelAdmin, 9, 0, 1, 1)
    self.horizontalLayout_10 = QtGui.QHBoxLayout()
    self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
    self.lineEditWorkers = QtGui.QLineEdit(self.centralwidget)
    self.lineEditWorkers.setEnabled(False)
    self.lineEditWorkers.setReadOnly(True)
    self.lineEditWorkers.setObjectName(_fromUtf8("lineEditWorkers"))
    self.horizontalLayout_10.addWidget(self.lineEditWorkers)
    self.checkAssignSelf = QtGui.QCheckBox(self.centralwidget)
    self.checkAssignSelf.setChecked(True)
    self.checkAssignSelf.setObjectName(_fromUtf8("checkAssignSelf"))
    self.horizontalLayout_10.addWidget(self.checkAssignSelf)
    self.pushUsers = QtGui.QPushButton(self.centralwidget)
    self.pushUsers.setEnabled(False)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushUsers.sizePolicy().hasHeightForWidth())
    self.pushUsers.setSizePolicy(sizePolicy)
    self.pushUsers.setObjectName(_fromUtf8("pushUsers"))
    self.horizontalLayout_10.addWidget(self.pushUsers)
    self.gridLayout.addLayout(self.horizontalLayout_10, 9, 1, 1, 1)
    self.labelReview = QtGui.QLabel(self.centralwidget)
    self.labelReview.setObjectName(_fromUtf8("labelReview"))
    self.gridLayout.addWidget(self.labelReview, 10, 0, 1, 1)
    self.horizontalLayout_11 = QtGui.QHBoxLayout()
    self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
    self.lineEditReviewers = QtGui.QLineEdit(self.centralwidget)
    self.lineEditReviewers.setEnabled(False)
    self.lineEditReviewers.setReadOnly(True)
    self.lineEditReviewers.setObjectName(_fromUtf8("lineEditReviewers"))
    self.horizontalLayout_11.addWidget(self.lineEditReviewers)
    self.checkReviewSelf = QtGui.QCheckBox(self.centralwidget)
    self.checkReviewSelf.setChecked(True)
    self.checkReviewSelf.setObjectName(_fromUtf8("checkReviewSelf"))
    self.horizontalLayout_11.addWidget(self.checkReviewSelf)
    self.pushReviewers = QtGui.QPushButton(self.centralwidget)
    self.pushReviewers.setEnabled(True)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushReviewers.sizePolicy().hasHeightForWidth())
    self.pushReviewers.setSizePolicy(sizePolicy)
    self.pushReviewers.setObjectName(_fromUtf8("pushReviewers"))
    self.horizontalLayout_11.addWidget(self.pushReviewers)
    self.gridLayout.addLayout(self.horizontalLayout_11, 10, 1, 1, 1)
    self.labelDesc = QtGui.QLabel(self.centralwidget)
    self.labelDesc.setObjectName(_fromUtf8("labelDesc"))
    self.gridLayout.addWidget(self.labelDesc, 11, 0, 1, 1)
    self.horizontalLayout_12 = QtGui.QHBoxLayout()
    self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
    self.lineEditDesc = QtGui.QLineEdit(self.centralwidget)
    self.lineEditDesc.setText(_fromUtf8(""))
    self.lineEditDesc.setObjectName(_fromUtf8("lineEditDesc"))
    self.horizontalLayout_12.addWidget(self.lineEditDesc)
    self.gridLayout.addLayout(self.horizontalLayout_12, 11, 1, 1, 1)
    self.labelTags = QtGui.QLabel(self.centralwidget)
    self.labelTags.setObjectName(_fromUtf8("labelTags"))
    self.gridLayout.addWidget(self.labelTags, 12, 0, 1, 1)
    self.horizontalLayout_13 = QtGui.QHBoxLayout()
    self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
    self.lineEditTags = QtGui.QLineEdit(self.centralwidget)
    self.lineEditTags.setObjectName(_fromUtf8("lineEditTags"))
    self.horizontalLayout_13.addWidget(self.lineEditTags)
    self.pushTags = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushTags.sizePolicy().hasHeightForWidth())
    self.pushTags.setSizePolicy(sizePolicy)
    self.pushTags.setObjectName(_fromUtf8("pushTags"))
    self.horizontalLayout_13.addWidget(self.pushTags)
    self.gridLayout.addLayout(self.horizontalLayout_13, 12, 1, 1, 1)
    self.labelVersion = QtGui.QLabel(self.centralwidget)
    self.labelVersion.setObjectName(_fromUtf8("labelVersion"))
    self.gridLayout.addWidget(self.labelVersion, 13, 0, 1, 1)
    self.horizontalLayout_14 = QtGui.QHBoxLayout()
    self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
    self.checkVersion = QtGui.QCheckBox(self.centralwidget)
    self.checkVersion.setText(_fromUtf8(""))
    self.checkVersion.setChecked(True)
    self.checkVersion.setObjectName(_fromUtf8("checkVersion"))
    self.horizontalLayout_14.addWidget(self.checkVersion)
    self.gridLayout.addLayout(self.horizontalLayout_14, 13, 1, 1, 1)
    self.line = QtGui.QFrame(self.centralwidget)
    self.line.setFrameShape(QtGui.QFrame.HLine)
    self.line.setFrameShadow(QtGui.QFrame.Sunken)
    self.line.setObjectName(_fromUtf8("line"))
    self.gridLayout.addWidget(self.line, 14, 0, 1, 2)
    self.pushCreate = QtGui.QPushButton(self.centralwidget)
    self.pushCreate.setObjectName(_fromUtf8("pushCreate"))
    self.gridLayout.addWidget(self.pushCreate, 15, 0, 1, 2)
    spacerItem = QtGui.QSpacerItem(454, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem, 16, 0, 1, 2)
    MainWindow.setCentralWidget(self.centralwidget)
    self.statusbar = QtGui.QStatusBar(MainWindow)
    self.statusbar.setObjectName(_fromUtf8("statusbar"))
    MainWindow.setStatusBar(self.statusbar)

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
    self.labelAssName.setText(_translate("MainWindow", "assetName", None))
    self.lineEditAssName.setToolTip(_translate("MainWindow", "comma seperated list of asset names", None))
    self.lineEditAssName.setStatusTip(_translate("MainWindow", "comma seperated list of asset names", None))
    self.pushAssets.setText(_translate("MainWindow", "select", None))
    self.labelAssType.setText(_translate("MainWindow", "assetType", None))
    self.labelDirectory.setWhatsThis(_translate("MainWindow", "directory to store the output data from file. eg : rendered output of lighting files.", None))
    self.labelDirectory.setText(_translate("MainWindow", "directory", None))
    self.labelSequence.setText(_translate("MainWindow", "sequence", None))
    self.labelScene.setText(_translate("MainWindow", "scene", None))
    self.pushScenes.setText(_translate("MainWindow", "select", None))
    self.lineEditScenes.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.lineEditScenes.setText(_translate("MainWindow", "default", None))
    self.labelStageType.setText(_translate("MainWindow", "stageType", None))
    self.labelNodeType.setText(_translate("MainWindow", "nodeType", None))
    self.pushNodes.setText(_translate("MainWindow", "select", None))
    self.lineEditNodes.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.lineEditNodes.setText(_translate("MainWindow", "default", None))
    self.labelFRange.setText(_translate("MainWindow", "fRange", None))
    self.lineEditFRange.setText(_translate("MainWindow", "1", None))
    self.labelDue.setText(_translate("MainWindow", "due date", None))
    self.labelAdmin.setText(_translate("MainWindow", "assign to", None))
    self.lineEditWorkers.setToolTip(_translate("MainWindow", "list of space separated usernames", None))
    self.checkAssignSelf.setText(_translate("MainWindow", "self", None))
    self.pushUsers.setText(_translate("MainWindow", "select", None))
    self.labelReview.setText(_translate("MainWindow", "reviewer", None))
    self.lineEditReviewers.setToolTip(_translate("MainWindow", "list of space separated usernames", None))
    self.checkReviewSelf.setText(_translate("MainWindow", "self", None))
    self.pushReviewers.setText(_translate("MainWindow", "select", None))
    self.labelDesc.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelDesc.setText(_translate("MainWindow", "description", None))
    self.lineEditDesc.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelTags.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelTags.setText(_translate("MainWindow", "tags", None))
    self.lineEditTags.setToolTip(_translate("MainWindow", "comma seperated list of tags", None))
    self.lineEditTags.setStatusTip(_translate("MainWindow", "comma seperated list of tags", None))
    self.lineEditTags.setText(_translate("MainWindow", "default", None))
    self.pushTags.setText(_translate("MainWindow", "select", None))
    self.labelVersion.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelVersion.setText(_translate("MainWindow", "versioning", None))
    self.pushCreate.setText(_translate("MainWindow", "create", None))

