# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusPipeAssetCreateMod.ui'
#
# Created: Wed Mar  4 22:13:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.setEnabled(True)
    MainWindow.resize(397, 420)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.checkAssName = QtGui.QCheckBox(self.centralwidget)
    self.checkAssName.setEnabled(True)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkAssName.sizePolicy().hasHeightForWidth())
    self.checkAssName.setSizePolicy(sizePolicy)
    self.checkAssName.setText(_fromUtf8(""))
    self.checkAssName.setChecked(False)
    self.checkAssName.setObjectName(_fromUtf8("checkAssName"))
    self.gridLayout.addWidget(self.checkAssName, 0, 4, 1, 1)
    self.labelStageType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelStageType.sizePolicy().hasHeightForWidth())
    self.labelStageType.setSizePolicy(sizePolicy)
    self.labelStageType.setObjectName(_fromUtf8("labelStageType"))
    self.gridLayout.addWidget(self.labelStageType, 7, 0, 1, 1)
    self.comboAssType = QtGui.QComboBox(self.centralwidget)
    self.comboAssType.setObjectName(_fromUtf8("comboAssType"))
    self.gridLayout.addWidget(self.comboAssType, 3, 1, 1, 4)
    spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem, 15, 0, 1, 5)
    self.comboDirectory = QtGui.QComboBox(self.centralwidget)
    self.comboDirectory.setObjectName(_fromUtf8("comboDirectory"))
    self.gridLayout.addWidget(self.comboDirectory, 2, 1, 1, 4)
    self.labelScene = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelScene.sizePolicy().hasHeightForWidth())
    self.labelScene.setSizePolicy(sizePolicy)
    self.labelScene.setObjectName(_fromUtf8("labelScene"))
    self.gridLayout.addWidget(self.labelScene, 5, 0, 1, 1)
    self.labelNodeType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelNodeType.sizePolicy().hasHeightForWidth())
    self.labelNodeType.setSizePolicy(sizePolicy)
    self.labelNodeType.setObjectName(_fromUtf8("labelNodeType"))
    self.gridLayout.addWidget(self.labelNodeType, 8, 0, 1, 1)
    self.labelAssType = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAssType.sizePolicy().hasHeightForWidth())
    self.labelAssType.setSizePolicy(sizePolicy)
    self.labelAssType.setObjectName(_fromUtf8("labelAssType"))
    self.gridLayout.addWidget(self.labelAssType, 3, 0, 1, 1)
    self.dateEditDue = QtGui.QDateTimeEdit(self.centralwidget)
    self.dateEditDue.setCalendarPopup(True)
    self.dateEditDue.setObjectName(_fromUtf8("dateEditDue"))
    self.gridLayout.addWidget(self.dateEditDue, 10, 1, 1, 4)
    self.checkAssignSelf = QtGui.QCheckBox(self.centralwidget)
    self.checkAssignSelf.setChecked(True)
    self.checkAssignSelf.setObjectName(_fromUtf8("checkAssignSelf"))
    self.gridLayout.addWidget(self.checkAssignSelf, 11, 2, 1, 1)
    self.lineEditDesc = QtGui.QLineEdit(self.centralwidget)
    self.lineEditDesc.setText(_fromUtf8(""))
    self.lineEditDesc.setObjectName(_fromUtf8("lineEditDesc"))
    self.gridLayout.addWidget(self.lineEditDesc, 12, 1, 1, 4)
    self.labelSequence = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelSequence.sizePolicy().hasHeightForWidth())
    self.labelSequence.setSizePolicy(sizePolicy)
    self.labelSequence.setObjectName(_fromUtf8("labelSequence"))
    self.gridLayout.addWidget(self.labelSequence, 4, 0, 1, 1)
    self.pushTags = QtGui.QPushButton(self.centralwidget)
    self.pushTags.setObjectName(_fromUtf8("pushTags"))
    self.gridLayout.addWidget(self.pushTags, 13, 4, 1, 1)
    self.labelDirectory = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDirectory.sizePolicy().hasHeightForWidth())
    self.labelDirectory.setSizePolicy(sizePolicy)
    self.labelDirectory.setObjectName(_fromUtf8("labelDirectory"))
    self.gridLayout.addWidget(self.labelDirectory, 2, 0, 1, 1)
    self.lineEditAssName = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditAssName.sizePolicy().hasHeightForWidth())
    self.lineEditAssName.setSizePolicy(sizePolicy)
    self.lineEditAssName.setObjectName(_fromUtf8("lineEditAssName"))
    self.gridLayout.addWidget(self.lineEditAssName, 0, 1, 1, 3)
    self.pushCreate = QtGui.QPushButton(self.centralwidget)
    self.pushCreate.setObjectName(_fromUtf8("pushCreate"))
    self.gridLayout.addWidget(self.pushCreate, 17, 0, 1, 5)
    self.labelAdmin = QtGui.QLabel(self.centralwidget)
    self.labelAdmin.setObjectName(_fromUtf8("labelAdmin"))
    self.gridLayout.addWidget(self.labelAdmin, 11, 0, 1, 1)
    self.labelTags = QtGui.QLabel(self.centralwidget)
    self.labelTags.setObjectName(_fromUtf8("labelTags"))
    self.gridLayout.addWidget(self.labelTags, 13, 0, 1, 1)
    self.pushUsers = QtGui.QPushButton(self.centralwidget)
    self.pushUsers.setEnabled(False)
    self.pushUsers.setObjectName(_fromUtf8("pushUsers"))
    self.gridLayout.addWidget(self.pushUsers, 11, 4, 1, 1)
    self.labelFRange = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelFRange.sizePolicy().hasHeightForWidth())
    self.labelFRange.setSizePolicy(sizePolicy)
    self.labelFRange.setObjectName(_fromUtf8("labelFRange"))
    self.gridLayout.addWidget(self.labelFRange, 9, 0, 1, 1)
    self.lineEditNodes = QtGui.QLineEdit(self.centralwidget)
    self.lineEditNodes.setReadOnly(True)
    self.lineEditNodes.setObjectName(_fromUtf8("lineEditNodes"))
    self.gridLayout.addWidget(self.lineEditNodes, 8, 1, 1, 3)
    self.labelDue = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDue.sizePolicy().hasHeightForWidth())
    self.labelDue.setSizePolicy(sizePolicy)
    self.labelDue.setObjectName(_fromUtf8("labelDue"))
    self.gridLayout.addWidget(self.labelDue, 10, 0, 1, 1)
    self.comboStageType = QtGui.QComboBox(self.centralwidget)
    self.comboStageType.setObjectName(_fromUtf8("comboStageType"))
    self.gridLayout.addWidget(self.comboStageType, 7, 1, 1, 4)
    self.lineEditWorkers = QtGui.QLineEdit(self.centralwidget)
    self.lineEditWorkers.setEnabled(False)
    self.lineEditWorkers.setReadOnly(True)
    self.lineEditWorkers.setObjectName(_fromUtf8("lineEditWorkers"))
    self.gridLayout.addWidget(self.lineEditWorkers, 11, 1, 1, 1)
    self.pushScenes = QtGui.QPushButton(self.centralwidget)
    self.pushScenes.setObjectName(_fromUtf8("pushScenes"))
    self.gridLayout.addWidget(self.pushScenes, 5, 4, 1, 1)
    self.pushNodes = QtGui.QPushButton(self.centralwidget)
    self.pushNodes.setObjectName(_fromUtf8("pushNodes"))
    self.gridLayout.addWidget(self.pushNodes, 8, 4, 1, 1)
    self.lineEditScenes = QtGui.QLineEdit(self.centralwidget)
    self.lineEditScenes.setReadOnly(True)
    self.lineEditScenes.setObjectName(_fromUtf8("lineEditScenes"))
    self.gridLayout.addWidget(self.lineEditScenes, 5, 1, 1, 3)
    self.lineEditFRange = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditFRange.sizePolicy().hasHeightForWidth())
    self.lineEditFRange.setSizePolicy(sizePolicy)
    self.lineEditFRange.setObjectName(_fromUtf8("lineEditFRange"))
    self.gridLayout.addWidget(self.lineEditFRange, 9, 1, 1, 4)
    self.line = QtGui.QFrame(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
    self.line.setSizePolicy(sizePolicy)
    self.line.setFrameShape(QtGui.QFrame.HLine)
    self.line.setFrameShadow(QtGui.QFrame.Sunken)
    self.line.setObjectName(_fromUtf8("line"))
    self.gridLayout.addWidget(self.line, 16, 0, 1, 5)
    self.labelDesc = QtGui.QLabel(self.centralwidget)
    self.labelDesc.setObjectName(_fromUtf8("labelDesc"))
    self.gridLayout.addWidget(self.labelDesc, 12, 0, 1, 1)
    self.comboSequence = QtGui.QComboBox(self.centralwidget)
    self.comboSequence.setObjectName(_fromUtf8("comboSequence"))
    self.gridLayout.addWidget(self.comboSequence, 4, 1, 1, 4)
    self.lineEditTags = QtGui.QLineEdit(self.centralwidget)
    self.lineEditTags.setObjectName(_fromUtf8("lineEditTags"))
    self.gridLayout.addWidget(self.lineEditTags, 13, 1, 1, 2)
    self.labelAssName = QtGui.QLabel(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAssName.sizePolicy().hasHeightForWidth())
    self.labelAssName.setSizePolicy(sizePolicy)
    self.labelAssName.setObjectName(_fromUtf8("labelAssName"))
    self.gridLayout.addWidget(self.labelAssName, 0, 0, 1, 1)
    self.labelVersion = QtGui.QLabel(self.centralwidget)
    self.labelVersion.setObjectName(_fromUtf8("labelVersion"))
    self.gridLayout.addWidget(self.labelVersion, 14, 0, 1, 1)
    self.checkVersion = QtGui.QCheckBox(self.centralwidget)
    self.checkVersion.setText(_fromUtf8(""))
    self.checkVersion.setChecked(False)
    self.checkVersion.setObjectName(_fromUtf8("checkVersion"))
    self.gridLayout.addWidget(self.checkVersion, 14, 1, 1, 1)
    MainWindow.setCentralWidget(self.centralwidget)
    self.statusBar = QtGui.QStatusBar(MainWindow)
    self.statusBar.setObjectName(_fromUtf8("statusBar"))
    MainWindow.setStatusBar(self.statusBar)

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(_translate("MainWindow", "Create Asset", None))
    self.labelStageType.setText(_translate("MainWindow", "stageType", None))
    self.labelScene.setText(_translate("MainWindow", "scene", None))
    self.labelNodeType.setText(_translate("MainWindow", "nodeType", None))
    self.labelAssType.setText(_translate("MainWindow", "assetType", None))
    self.checkAssignSelf.setText(_translate("MainWindow", "self", None))
    self.lineEditDesc.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelSequence.setText(_translate("MainWindow", "sequence", None))
    self.pushTags.setText(_translate("MainWindow", "select", None))
    self.labelDirectory.setWhatsThis(_translate("MainWindow", "directory to store the output data from file. eg : rendered output of lighting files.", None))
    self.labelDirectory.setText(_translate("MainWindow", "directory", None))
    self.lineEditAssName.setToolTip(_translate("MainWindow", "comma seperated list of asset names", None))
    self.lineEditAssName.setStatusTip(_translate("MainWindow", "comma seperated list of asset names", None))
    self.pushCreate.setText(_translate("MainWindow", "create", None))
    self.labelAdmin.setText(_translate("MainWindow", "assign to", None))
    self.labelTags.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelTags.setText(_translate("MainWindow", "tags", None))
    self.pushUsers.setText(_translate("MainWindow", "select", None))
    self.labelFRange.setText(_translate("MainWindow", "fRange", None))
    self.lineEditNodes.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.lineEditNodes.setText(_translate("MainWindow", "default", None))
    self.labelDue.setText(_translate("MainWindow", "due date", None))
    self.lineEditWorkers.setToolTip(_translate("MainWindow", "list of space separated usernames", None))
    self.pushScenes.setText(_translate("MainWindow", "select", None))
    self.pushNodes.setText(_translate("MainWindow", "select", None))
    self.lineEditScenes.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.lineEditScenes.setText(_translate("MainWindow", "default", None))
    self.lineEditFRange.setText(_translate("MainWindow", "1", None))
    self.labelDesc.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelDesc.setText(_translate("MainWindow", "description", None))
    self.lineEditTags.setToolTip(_translate("MainWindow", "comma seperated list of tags", None))
    self.lineEditTags.setStatusTip(_translate("MainWindow", "comma seperated list of tags", None))
    self.lineEditTags.setText(_translate("MainWindow", "default", None))
    self.labelAssName.setText(_translate("MainWindow", "assetName", None))
    self.labelVersion.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelVersion.setText(_translate("MainWindow", "versioning", None))

