# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusPipeMainMod.ui'
#
# Created: Thu Aug  7 14:21:09 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(966, 621)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
    MainWindow.setSizePolicy(sizePolicy)
    MainWindow.setDocumentMode(False)
    MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.checkRefresh = QtGui.QCheckBox(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkRefresh.sizePolicy().hasHeightForWidth())
    self.checkRefresh.setSizePolicy(sizePolicy)
    self.checkRefresh.setText(_fromUtf8(""))
    self.checkRefresh.setIconSize(QtCore.QSize(20, 20))
    self.checkRefresh.setObjectName(_fromUtf8("checkRefresh"))
    self.gridLayout.addWidget(self.checkRefresh, 13, 3, 1, 1)
    self.line = QtGui.QFrame(self.centralwidget)
    self.line.setEnabled(True)
    self.line.setFrameShadow(QtGui.QFrame.Sunken)
    self.line.setLineWidth(1)
    self.line.setMidLineWidth(3)
    self.line.setFrameShape(QtGui.QFrame.HLine)
    self.line.setFrameShadow(QtGui.QFrame.Sunken)
    self.line.setObjectName(_fromUtf8("line"))
    self.gridLayout.addWidget(self.line, 12, 0, 1, 5)
    self.groupBoxFilter = QtGui.QGroupBox(self.centralwidget)
    self.groupBoxFilter.setEnabled(True)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.groupBoxFilter.sizePolicy().hasHeightForWidth())
    self.groupBoxFilter.setSizePolicy(sizePolicy)
    self.groupBoxFilter.setTitle(_fromUtf8(""))
    self.groupBoxFilter.setAlignment(QtCore.Qt.AlignCenter)
    self.groupBoxFilter.setFlat(False)
    self.groupBoxFilter.setCheckable(False)
    self.groupBoxFilter.setChecked(False)
    self.groupBoxFilter.setObjectName(_fromUtf8("groupBoxFilter"))
    self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxFilter)
    self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
    self.labelSce = QtGui.QLabel(self.groupBoxFilter)
    self.labelSce.setObjectName(_fromUtf8("labelSce"))
    self.gridLayout_2.addWidget(self.labelSce, 3, 2, 1, 1)
    self.comboSequence = QtGui.QComboBox(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboSequence.sizePolicy().hasHeightForWidth())
    self.comboSequence.setSizePolicy(sizePolicy)
    self.comboSequence.setObjectName(_fromUtf8("comboSequence"))
    self.gridLayout_2.addWidget(self.comboSequence, 4, 1, 1, 1)
    self.labelAssType = QtGui.QLabel(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAssType.sizePolicy().hasHeightForWidth())
    self.labelAssType.setSizePolicy(sizePolicy)
    self.labelAssType.setObjectName(_fromUtf8("labelAssType"))
    self.gridLayout_2.addWidget(self.labelAssType, 1, 1, 1, 1)
    self.label = QtGui.QLabel(self.groupBoxFilter)
    self.label.setObjectName(_fromUtf8("label"))
    self.gridLayout_2.addWidget(self.label, 5, 1, 1, 1)
    self.label_2 = QtGui.QLabel(self.groupBoxFilter)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.gridLayout_2.addWidget(self.label_2, 5, 2, 1, 1)
    self.comboScene = QtGui.QComboBox(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboScene.sizePolicy().hasHeightForWidth())
    self.comboScene.setSizePolicy(sizePolicy)
    self.comboScene.setObjectName(_fromUtf8("comboScene"))
    self.gridLayout_2.addWidget(self.comboScene, 4, 2, 1, 1)
    self.comboNodeType = QtGui.QComboBox(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboNodeType.sizePolicy().hasHeightForWidth())
    self.comboNodeType.setSizePolicy(sizePolicy)
    self.comboNodeType.setObjectName(_fromUtf8("comboNodeType"))
    self.gridLayout_2.addWidget(self.comboNodeType, 6, 2, 1, 1)
    self.comboStageType = QtGui.QComboBox(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboStageType.sizePolicy().hasHeightForWidth())
    self.comboStageType.setSizePolicy(sizePolicy)
    self.comboStageType.setObjectName(_fromUtf8("comboStageType"))
    self.gridLayout_2.addWidget(self.comboStageType, 6, 1, 1, 1)
    self.comboAssType = QtGui.QComboBox(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboAssType.sizePolicy().hasHeightForWidth())
    self.comboAssType.setSizePolicy(sizePolicy)
    self.comboAssType.setObjectName(_fromUtf8("comboAssType"))
    self.gridLayout_2.addWidget(self.comboAssType, 2, 1, 1, 1)
    self.labelFileType = QtGui.QLabel(self.groupBoxFilter)
    self.labelFileType.setObjectName(_fromUtf8("labelFileType"))
    self.gridLayout_2.addWidget(self.labelFileType, 5, 3, 1, 1)
    self.comboFileType = QtGui.QComboBox(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.comboFileType.sizePolicy().hasHeightForWidth())
    self.comboFileType.setSizePolicy(sizePolicy)
    self.comboFileType.setObjectName(_fromUtf8("comboFileType"))
    self.gridLayout_2.addWidget(self.comboFileType, 6, 3, 1, 1)
    self.labelSeq = QtGui.QLabel(self.groupBoxFilter)
    self.labelSeq.setObjectName(_fromUtf8("labelSeq"))
    self.gridLayout_2.addWidget(self.labelSeq, 3, 1, 1, 1)
    self.horizontalLayout_2 = QtGui.QHBoxLayout()
    self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout_2.addItem(spacerItem)
    self.filterRefresh = QtGui.QPushButton(self.groupBoxFilter)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.filterRefresh.sizePolicy().hasHeightForWidth())
    self.filterRefresh.setSizePolicy(sizePolicy)
    self.filterRefresh.setText(_fromUtf8(""))
    self.filterRefresh.setObjectName(_fromUtf8("filterRefresh"))
    self.horizontalLayout_2.addWidget(self.filterRefresh)
    self.gridLayout_2.addLayout(self.horizontalLayout_2, 7, 3, 1, 1)
    self.gridLayout.addWidget(self.groupBoxFilter, 1, 0, 1, 4)
    self.listWidget = QtGui.QListWidget(self.centralwidget)
    palette = QtGui.QPalette()
    brush = QtGui.QBrush(QtGui.QColor(176, 176, 176))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
    brush = QtGui.QBrush(QtGui.QColor(176, 176, 176))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
    brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
    brush.setStyle(QtCore.Qt.SolidPattern)
    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
    self.listWidget.setPalette(palette)
    self.listWidget.setAutoFillBackground(False)
    self.listWidget.setFrameShape(QtGui.QFrame.StyledPanel)
    self.listWidget.setFrameShadow(QtGui.QFrame.Raised)
    self.listWidget.setMidLineWidth(1)
    self.listWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
    self.listWidget.setAlternatingRowColors(False)
    self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
    self.listWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
    self.listWidget.setMovement(QtGui.QListView.Static)
    self.listWidget.setResizeMode(QtGui.QListView.Adjust)
    self.listWidget.setLayoutMode(QtGui.QListView.SinglePass)
    self.listWidget.setSpacing(4)
    self.listWidget.setViewMode(QtGui.QListView.ListMode)
    self.listWidget.setUniformItemSizes(True)
    self.listWidget.setSelectionRectVisible(False)
    self.listWidget.setObjectName(_fromUtf8("listWidget"))
    self.gridLayout.addWidget(self.listWidget, 10, 0, 1, 5)
    self.pushLogout = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushLogout.sizePolicy().hasHeightForWidth())
    self.pushLogout.setSizePolicy(sizePolicy)
    self.pushLogout.setObjectName(_fromUtf8("pushLogout"))
    self.gridLayout.addWidget(self.pushLogout, 13, 0, 1, 1)
    self.horizontalLayout = QtGui.QHBoxLayout()
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.pushNewAsset = QtGui.QPushButton(self.centralwidget)
    self.pushNewAsset.setObjectName(_fromUtf8("pushNewAsset"))
    self.horizontalLayout.addWidget(self.pushNewAsset)
    self.radioMineAss = QtGui.QRadioButton(self.centralwidget)
    self.radioMineAss.setChecked(True)
    self.radioMineAss.setObjectName(_fromUtf8("radioMineAss"))
    self.horizontalLayout.addWidget(self.radioMineAss)
    self.radioAllAss = QtGui.QRadioButton(self.centralwidget)
    self.radioAllAss.setObjectName(_fromUtf8("radioAllAss"))
    self.horizontalLayout.addWidget(self.radioAllAss)
    spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem1)
    self.lineEditSearch = QtGui.QLineEdit(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditSearch.sizePolicy().hasHeightForWidth())
    self.lineEditSearch.setSizePolicy(sizePolicy)
    self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
    self.horizontalLayout.addWidget(self.lineEditSearch)
    self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 5)
    self.checkBoxFilter = QtGui.QCheckBox(self.centralwidget)
    self.checkBoxFilter.setObjectName(_fromUtf8("checkBoxFilter"))
    self.gridLayout.addWidget(self.checkBoxFilter, 1, 4, 1, 1)
    self.assRefresh = QtGui.QPushButton(self.centralwidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.assRefresh.sizePolicy().hasHeightForWidth())
    self.assRefresh.setSizePolicy(sizePolicy)
    self.assRefresh.setText(_fromUtf8(""))
    self.assRefresh.setObjectName(_fromUtf8("assRefresh"))
    self.gridLayout.addWidget(self.assRefresh, 13, 4, 1, 1)
    spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.gridLayout.addItem(spacerItem2, 13, 1, 1, 2)
    MainWindow.setCentralWidget(self.centralwidget)
    self.menuBar = QtGui.QMenuBar(MainWindow)
    self.menuBar.setGeometry(QtCore.QRect(0, 0, 966, 21))
    self.menuBar.setObjectName(_fromUtf8("menuBar"))
    self.menuAdmin = QtGui.QMenu(self.menuBar)
    self.menuAdmin.setObjectName(_fromUtf8("menuAdmin"))
    self.menuProject = QtGui.QMenu(self.menuBar)
    self.menuProject.setObjectName(_fromUtf8("menuProject"))
    self.menuDebug = QtGui.QMenu(self.menuBar)
    self.menuDebug.setObjectName(_fromUtf8("menuDebug"))
    MainWindow.setMenuBar(self.menuBar)
    self.actionMine = QtGui.QAction(MainWindow)
    self.actionMine.setObjectName(_fromUtf8("actionMine"))
    self.actionAll = QtGui.QAction(MainWindow)
    self.actionAll.setObjectName(_fromUtf8("actionAll"))
    self.actionSet_project = QtGui.QAction(MainWindow)
    self.actionSet_project.setObjectName(_fromUtf8("actionSet_project"))
    self.actionTask_trak = QtGui.QAction(MainWindow)
    self.actionTask_trak.setObjectName(_fromUtf8("actionTask_trak"))
    self.actionNew_project = QtGui.QAction(MainWindow)
    self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
    self.actionList_env = QtGui.QAction(MainWindow)
    self.actionList_env.setObjectName(_fromUtf8("actionList_env"))
    self.actionNew_seq_scn = QtGui.QAction(MainWindow)
    self.actionNew_seq_scn.setObjectName(_fromUtf8("actionNew_seq_scn"))
    self.menuAdmin.addAction(self.actionTask_trak)
    self.menuAdmin.addAction(self.actionNew_seq_scn)
    self.menuProject.addAction(self.actionSet_project)
    self.menuProject.addAction(self.actionNew_project)
    self.menuDebug.addAction(self.actionList_env)
    self.menuBar.addAction(self.menuProject.menuAction())
    self.menuBar.addAction(self.menuAdmin.menuAction())
    self.menuBar.addAction(self.menuDebug.menuAction())

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(_translate("MainWindow", "Rbhus Production Management", None))
    self.labelSce.setText(_translate("MainWindow", "scene", None))
    self.labelAssType.setText(_translate("MainWindow", "assetType", None))
    self.label.setText(_translate("MainWindow", "stageType", None))
    self.label_2.setText(_translate("MainWindow", "nodeType", None))
    self.labelFileType.setText(_translate("MainWindow", "fileType", None))
    self.labelSeq.setText(_translate("MainWindow", "sequence", None))
    self.listWidget.setSortingEnabled(True)
    self.pushLogout.setText(_translate("MainWindow", "logout", None))
    self.pushNewAsset.setText(_translate("MainWindow", "new", None))
    self.radioMineAss.setText(_translate("MainWindow", "mine", None))
    self.radioAllAss.setText(_translate("MainWindow", "all", None))
    self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "search", None))
    self.checkBoxFilter.setText(_translate("MainWindow", "filters", None))
    self.menuAdmin.setTitle(_translate("MainWindow", "admin", None))
    self.menuProject.setTitle(_translate("MainWindow", "project", None))
    self.menuDebug.setTitle(_translate("MainWindow", "debug", None))
    self.actionMine.setText(_translate("MainWindow", "mine", None))
    self.actionAll.setText(_translate("MainWindow", "all", None))
    self.actionSet_project.setText(_translate("MainWindow", "set project", None))
    self.actionTask_trak.setText(_translate("MainWindow", "trak", None))
    self.actionNew_project.setText(_translate("MainWindow", "new project", None))
    self.actionList_env.setText(_translate("MainWindow", "list env", None))
    self.actionNew_seq_scn.setText(_translate("MainWindow", "new seq/scn", None))

