# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbhusPipeAssetEditMod.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtWidgets, QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtWidgets.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.setEnabled(True)
    MainWindow.resize(441, 361)
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setEnabled(True)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
    # self.gridLayout.setMargin(1)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.checkDueDate = QtWidgets.QCheckBox(self.centralwidget)
    self.checkDueDate.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkDueDate.sizePolicy().hasHeightForWidth())
    self.checkDueDate.setSizePolicy(sizePolicy)
    self.checkDueDate.setText(_fromUtf8(""))
    self.checkDueDate.setChecked(False)
    self.checkDueDate.setObjectName(_fromUtf8("checkDueDate"))
    self.gridLayout.addWidget(self.checkDueDate, 4, 7, 1, 1)
    self.labelDesc = QtWidgets.QLabel(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDesc.sizePolicy().hasHeightForWidth())
    self.labelDesc.setSizePolicy(sizePolicy)
    self.labelDesc.setObjectName(_fromUtf8("labelDesc"))
    self.gridLayout.addWidget(self.labelDesc, 9, 0, 1, 1)
    self.checkVersion = QtWidgets.QCheckBox(self.centralwidget)
    self.checkVersion.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkVersion.sizePolicy().hasHeightForWidth())
    self.checkVersion.setSizePolicy(sizePolicy)
    self.checkVersion.setText(_fromUtf8(""))
    self.checkVersion.setChecked(False)
    self.checkVersion.setObjectName(_fromUtf8("checkVersion"))
    self.gridLayout.addWidget(self.checkVersion, 13, 7, 1, 1)
    self.checkDesc = QtWidgets.QCheckBox(self.centralwidget)
    self.checkDesc.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkDesc.sizePolicy().hasHeightForWidth())
    self.checkDesc.setSizePolicy(sizePolicy)
    self.checkDesc.setText(_fromUtf8(""))
    self.checkDesc.setChecked(False)
    self.checkDesc.setObjectName(_fromUtf8("checkDesc"))
    self.gridLayout.addWidget(self.checkDesc, 9, 7, 1, 1)
    self.labelAssignTo = QtWidgets.QLabel(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelAssignTo.sizePolicy().hasHeightForWidth())
    self.labelAssignTo.setSizePolicy(sizePolicy)
    self.labelAssignTo.setObjectName(_fromUtf8("labelAssignTo"))
    self.gridLayout.addWidget(self.labelAssignTo, 6, 0, 1, 1)
    self.pushReviewers = QtWidgets.QPushButton(self.centralwidget)
    self.pushReviewers.setEnabled(True)
    self.pushReviewers.setObjectName(_fromUtf8("pushReviewers"))
    self.gridLayout.addWidget(self.pushReviewers, 7, 6, 1, 1)
    self.pushTags = QtWidgets.QPushButton(self.centralwidget)
    self.pushTags.setObjectName(_fromUtf8("pushTags"))
    self.gridLayout.addWidget(self.pushTags, 12, 6, 1, 1)
    self.pushUsers = QtWidgets.QPushButton(self.centralwidget)
    self.pushUsers.setObjectName(_fromUtf8("pushUsers"))
    self.gridLayout.addWidget(self.pushUsers, 6, 6, 1, 1)
    self.checkReview = QtWidgets.QCheckBox(self.centralwidget)
    self.checkReview.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkReview.sizePolicy().hasHeightForWidth())
    self.checkReview.setSizePolicy(sizePolicy)
    self.checkReview.setText(_fromUtf8(""))
    self.checkReview.setChecked(False)
    self.checkReview.setObjectName(_fromUtf8("checkReview"))
    self.gridLayout.addWidget(self.checkReview, 7, 7, 1, 1)
    self.labelReview = QtWidgets.QLabel(self.centralwidget)
    self.labelReview.setObjectName(_fromUtf8("labelReview"))
    self.gridLayout.addWidget(self.labelReview, 7, 0, 1, 1)
    self.lineEditWorkers = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditWorkers.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditWorkers.sizePolicy().hasHeightForWidth())
    self.lineEditWorkers.setSizePolicy(sizePolicy)
    self.lineEditWorkers.setObjectName(_fromUtf8("lineEditWorkers"))
    self.gridLayout.addWidget(self.lineEditWorkers, 6, 1, 1, 4)
    self.checkVersionEnable = QtWidgets.QCheckBox(self.centralwidget)
    self.checkVersionEnable.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkVersionEnable.sizePolicy().hasHeightForWidth())
    self.checkVersionEnable.setSizePolicy(sizePolicy)
    self.checkVersionEnable.setText(_fromUtf8(""))
    self.checkVersionEnable.setChecked(False)
    self.checkVersionEnable.setObjectName(_fromUtf8("checkVersionEnable"))
    self.gridLayout.addWidget(self.checkVersionEnable, 13, 1, 1, 1)
    self.labelVersion = QtWidgets.QLabel(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelVersion.sizePolicy().hasHeightForWidth())
    self.labelVersion.setSizePolicy(sizePolicy)
    self.labelVersion.setObjectName(_fromUtf8("labelVersion"))
    self.gridLayout.addWidget(self.labelVersion, 13, 0, 1, 1)
    self.checkReviewSelf = QtWidgets.QCheckBox(self.centralwidget)
    self.checkReviewSelf.setChecked(False)
    self.checkReviewSelf.setObjectName(_fromUtf8("checkReviewSelf"))
    self.gridLayout.addWidget(self.checkReviewSelf, 7, 5, 1, 1)
    self.checkAssign = QtWidgets.QCheckBox(self.centralwidget)
    self.checkAssign.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkAssign.sizePolicy().hasHeightForWidth())
    self.checkAssign.setSizePolicy(sizePolicy)
    self.checkAssign.setText(_fromUtf8(""))
    self.checkAssign.setChecked(False)
    self.checkAssign.setObjectName(_fromUtf8("checkAssign"))
    self.gridLayout.addWidget(self.checkAssign, 6, 7, 1, 1)
    self.checkFRange = QtWidgets.QCheckBox(self.centralwidget)
    self.checkFRange.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkFRange.sizePolicy().hasHeightForWidth())
    self.checkFRange.setSizePolicy(sizePolicy)
    self.checkFRange.setText(_fromUtf8(""))
    self.checkFRange.setChecked(False)
    self.checkFRange.setObjectName(_fromUtf8("checkFRange"))
    self.gridLayout.addWidget(self.checkFRange, 2, 7, 1, 1)
    self.labelFRange = QtWidgets.QLabel(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelFRange.sizePolicy().hasHeightForWidth())
    self.labelFRange.setSizePolicy(sizePolicy)
    self.labelFRange.setObjectName(_fromUtf8("labelFRange"))
    self.gridLayout.addWidget(self.labelFRange, 2, 0, 1, 1)
    self.checkTags = QtWidgets.QCheckBox(self.centralwidget)
    self.checkTags.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkTags.sizePolicy().hasHeightForWidth())
    self.checkTags.setSizePolicy(sizePolicy)
    self.checkTags.setText(_fromUtf8(""))
    self.checkTags.setChecked(False)
    self.checkTags.setObjectName(_fromUtf8("checkTags"))
    self.gridLayout.addWidget(self.checkTags, 12, 7, 1, 1)
    self.labelDue = QtWidgets.QLabel(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelDue.sizePolicy().hasHeightForWidth())
    self.labelDue.setSizePolicy(sizePolicy)
    self.labelDue.setObjectName(_fromUtf8("labelDue"))
    self.gridLayout.addWidget(self.labelDue, 4, 0, 1, 1)
    spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem, 14, 0, 1, 7)
    self.lineEditTags = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditTags.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditTags.sizePolicy().hasHeightForWidth())
    self.lineEditTags.setSizePolicy(sizePolicy)
    self.lineEditTags.setObjectName(_fromUtf8("lineEditTags"))
    self.gridLayout.addWidget(self.lineEditTags, 12, 1, 1, 5)
    self.checkAssignSelf = QtWidgets.QCheckBox(self.centralwidget)
    self.checkAssignSelf.setChecked(False)
    self.checkAssignSelf.setObjectName(_fromUtf8("checkAssignSelf"))
    self.gridLayout.addWidget(self.checkAssignSelf, 6, 5, 1, 1)
    self.labelTags = QtWidgets.QLabel(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.labelTags.sizePolicy().hasHeightForWidth())
    self.labelTags.setSizePolicy(sizePolicy)
    self.labelTags.setObjectName(_fromUtf8("labelTags"))
    self.gridLayout.addWidget(self.labelTags, 12, 0, 1, 1)
    self.lineEditDesc = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditDesc.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditDesc.sizePolicy().hasHeightForWidth())
    self.lineEditDesc.setSizePolicy(sizePolicy)
    self.lineEditDesc.setText(_fromUtf8(""))
    self.lineEditDesc.setObjectName(_fromUtf8("lineEditDesc"))
    self.gridLayout.addWidget(self.lineEditDesc, 9, 1, 1, 5)
    self.lineEditReviewers = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditReviewers.setEnabled(False)
    self.lineEditReviewers.setReadOnly(True)
    self.lineEditReviewers.setObjectName(_fromUtf8("lineEditReviewers"))
    self.gridLayout.addWidget(self.lineEditReviewers, 7, 1, 1, 4)
    self.lineEditFRange = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditFRange.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lineEditFRange.sizePolicy().hasHeightForWidth())
    self.lineEditFRange.setSizePolicy(sizePolicy)
    self.lineEditFRange.setObjectName(_fromUtf8("lineEditFRange"))
    self.gridLayout.addWidget(self.lineEditFRange, 2, 1, 1, 6)
    self.dateEditDue = QtWidgets.QDateTimeEdit(self.centralwidget)
    self.dateEditDue.setEnabled(False)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.dateEditDue.sizePolicy().hasHeightForWidth())
    self.dateEditDue.setSizePolicy(sizePolicy)
    self.dateEditDue.setCalendarPopup(True)
    self.dateEditDue.setObjectName(_fromUtf8("dateEditDue"))
    self.gridLayout.addWidget(self.dateEditDue, 4, 1, 1, 6)
    self.pushEdit = QtWidgets.QPushButton(self.centralwidget)
    self.pushEdit.setObjectName(_fromUtf8("pushEdit"))
    self.gridLayout.addWidget(self.pushEdit, 16, 0, 1, 8)
    self.line = QtWidgets.QFrame(self.centralwidget)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
    self.line.setSizePolicy(sizePolicy)
    self.line.setFrameShape(QtWidgets.QFrame.HLine)
    self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.line.setObjectName(_fromUtf8("line"))
    self.gridLayout.addWidget(self.line, 15, 0, 1, 8)
    self.labelReviewNotify = QtWidgets.QLabel(self.centralwidget)
    self.labelReviewNotify.setObjectName(_fromUtf8("labelReviewNotify"))
    self.gridLayout.addWidget(self.labelReviewNotify, 8, 0, 1, 1)
    self.lineEditReviewNotifiers = QtWidgets.QLineEdit(self.centralwidget)
    self.lineEditReviewNotifiers.setEnabled(False)
    self.lineEditReviewNotifiers.setReadOnly(True)
    self.lineEditReviewNotifiers.setObjectName(_fromUtf8("lineEditReviewNotifiers"))
    self.gridLayout.addWidget(self.lineEditReviewNotifiers, 8, 1, 1, 5)
    self.pushReviewNotifiers = QtWidgets.QPushButton(self.centralwidget)
    self.pushReviewNotifiers.setEnabled(True)
    self.pushReviewNotifiers.setObjectName(_fromUtf8("pushReviewNotifiers"))
    self.gridLayout.addWidget(self.pushReviewNotifiers, 8, 6, 1, 1)
    self.checkReviewNotifiers = QtWidgets.QCheckBox(self.centralwidget)
    self.checkReviewNotifiers.setEnabled(True)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.checkReviewNotifiers.sizePolicy().hasHeightForWidth())
    self.checkReviewNotifiers.setSizePolicy(sizePolicy)
    self.checkReviewNotifiers.setText(_fromUtf8(""))
    self.checkReviewNotifiers.setChecked(False)
    self.checkReviewNotifiers.setObjectName(_fromUtf8("checkReviewNotifiers"))
    self.gridLayout.addWidget(self.checkReviewNotifiers, 8, 7, 1, 1)
    MainWindow.setCentralWidget(self.centralwidget)
    self.statusBar = QtWidgets.QStatusBar(MainWindow)
    self.statusBar.setObjectName(_fromUtf8("statusBar"))
    MainWindow.setStatusBar(self.statusBar)

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(_translate("MainWindow", "Edit Asset", None))
    self.labelDesc.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelDesc.setText(_translate("MainWindow", "description", None))
    self.labelAssignTo.setText(_translate("MainWindow", "assign to", None))
    self.pushReviewers.setText(_translate("MainWindow", "select", None))
    self.pushTags.setText(_translate("MainWindow", "select", None))
    self.pushUsers.setText(_translate("MainWindow", "select", None))
    self.labelReview.setText(_translate("MainWindow", "reviewer", None))
    self.lineEditWorkers.setToolTip(_translate("MainWindow", "list of space separated usernames", None))
    self.lineEditWorkers.setText(_translate("MainWindow", "default", None))
    self.labelVersion.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelVersion.setText(_translate("MainWindow", "versioning", None))
    self.checkReviewSelf.setText(_translate("MainWindow", "self", None))
    self.labelFRange.setText(_translate("MainWindow", "fRange", None))
    self.labelDue.setText(_translate("MainWindow", "due date", None))
    self.lineEditTags.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.lineEditTags.setText(_translate("MainWindow", "default", None))
    self.checkAssignSelf.setText(_translate("MainWindow", "self", None))
    self.labelTags.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.labelTags.setText(_translate("MainWindow", "tags", None))
    self.lineEditDesc.setToolTip(_translate("MainWindow", "group owner of the project directory", None))
    self.lineEditReviewers.setToolTip(_translate("MainWindow", "list of space separated usernames", None))
    self.lineEditReviewers.setText(_translate("MainWindow", "default", None))
    self.lineEditFRange.setText(_translate("MainWindow", "1", None))
    self.pushEdit.setText(_translate("MainWindow", "edit", None))
    self.labelReviewNotify.setText(_translate("MainWindow", "review notify users", None))
    self.lineEditReviewNotifiers.setToolTip(_translate("MainWindow", "list of space separated usernames", None))
    self.lineEditReviewNotifiers.setText(_translate("MainWindow", "default", None))
    self.pushReviewNotifiers.setText(_translate("MainWindow", "select", None))

