#!/usr/bin/env bash
yes|parted /dev/sda mklabel msdos
partprobe

fdisk /dev/sda -l -o device | egrep 'sda[0-9].*' | sed 's/\/dev\/sda//g' | gawk '{print "parted -s /dev/sda rm "$1}' | sh -v

fdisk /dev/sda <<EOF
n
p


+1G
n
p


+32G
n
p



w
EOF
partprobe

fdisk /dev/sda <<EOF
x
A
1
r
w
EOF
partprobe

yes|parted /dev/sda set 1 boot on
partprobe



mkfs.ext4 /dev/sda1 -L bp_boot
mkswap /dev/sda2 -L bp_swap
mkfs.ext4 /dev/sda3 -L bp_root
exit 0