#!/usr/bin/env bash

mkdir -pv /mnt/realroot/
mount /dev/sda3 /mnt/realroot/
mkdir -pv /mnt/realroot/boot/
mount /dev/sda1 /mnt/realroot/boot/

mkdir -p /mnt/cloneMaster/
mount cloneMaster:/cloneMaster/ /mnt/cloneMaster/
mkdir -p /mnt/gentooOnesis-gentoo/
mount cloneMaster:/crap/gentooOnesis-gentoo/ /mnt/gentooOnesis-gentoo/
exit 0
