#!/usr/bin/env bash

mkdir -pv /mnt/realroot/
mount /dev/sda3 /mnt/realroot/
mkdir -pv /mnt/realroot/boot/
mount /dev/sda1 /mnt/realroot/boot/

mkdir -p /mnt/cloneMaster/
mount cloneMaster:/cloneMaster/ /mnt/cloneMaster/
mkdir -p /mnt/gentooOnesis-network/
mount cloneMaster:/crap/gentooOnesis-network/ /mnt/gentooOnesis-network/
exit 0
